security:
    encoders:
        Niouts\MainBundle\Entity\Utilisateur:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN ]

    providers:
        administrators:
            entity: { class: Niouts\MainBundle\Entity\Utilisateur, property: code }
    
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /connexion
                check_path:  /connexionCheck
            logout: ~
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~             
        
    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] } 
